---
title: "Linguagem R"
description: Conceitos básicos para o curso
---

```{r setup, include=FALSE}
library(knitr)
```

## Visão geral do R e RStudio

### **Porque usar o R em Hidrologia? **
- Simplicidade da linguagem

- Excelente desempenho na manipulação de grandes bancos de dados

- Acesso a métodos estatísticos consolidados

- Acesso a diversas ferramentas de visualização de dados

- Acesso a métodos analíticos de ponta e ferramentas compartilhadas internacionalmente - não só pelo uso de pacotes, mas sobretudo, usando fóruns e tutoriais.

- <a href="https://hess.copernicus.org/articles/23/2939/2019/hess-23-2939-2019.pdf"> R in Hydrology </a>, Slater, et al., Hydrol. Earth Syst. Sci., 23, 2939–2963, 2019.

## Primeiros passos

### Input/output

É imprescindível que a gente entenda como ler informações hidrológicas dos mais diversos tipos de arquivo, assim como aprender como escrever os resultados de nossas análises de forma organizada em aruivos de diferentes formatos para que possamos comunicar nossos resultados e para que outros possam avaliar e/ou continuar nossas análises.

Para isso, investiremos um tempo discutindo algumas maneiras de ler e escrever em arquivos fazendo uso de funções do R.

### Vetores


### Classes na linguagem R

### Criação de variáveis e atribuição de valores

### Dataframes

### Construção de gráficos

## Alguns pacotes

