---
title: "Análise exploratória dos dados"
description: Como obter uma visão geral dos dados
---

```{r setup, include=FALSE}
library(knitr)
```

## Plotagem da série histórica

```{r dados_hidro_ANA_2, echo=FALSE}
# Função para obter série histórica de vazão de uma determinada estação ####
dados_serie_ANA <- function(cod_estacao = NA,
                            data_inicio = "01/01/1800",
                            data_fim = Sys.Date(),
                            tipo_dados = 3,
                            nivel_consist = 1){
  
  # Pegar dados a partir do url e transformar em um dataframe
  url_base <-
    paste0("http://telemetriaws1.ana.gov.br/ServiceANA.asmx/",
           "HidroSerieHistorica?",
           "codEstacao=", cod_estacao,
           "&dataInicio=", data_inicio,
           "&dataFim=", data_fim,
           "&tipoDados=", tipo_dados,
           "&nivelConsistencia=", nivel_consist)
  
  url_parse <- XML::xmlParse(url_base, encoding = "UTF-8")
  node_doc <- XML::getNodeSet(url_parse, "//SerieHistorica")
  dados_estacao <- XML::xmlToDataFrame(nodes = node_doc)
  
  # Por algum motivo o hidroweb não está filtrando os dados pela consistencia
  dados_estacao <- filter(dados_estacao, NivelConsistencia == nivel_consist)
  
  # Separar data e hora
  dados_estacao$Data <- as.Date(substr(dados_estacao$DataHora, 1, 10))
  dados_estacao$Hora <- substr(dados_estacao$DataHora, 12, 19)
  
  # Fazer um dataframe só com datas e valores de vazão
  datas_dia <- seq.Date(from = min(dados_estacao$Data),
                        to = max(dados_estacao$Data) %m+% months(1) - 1,
                        by = "day")
  
  tabela_final <- data.frame(Cod_estacao = dados_estacao$EstacaoCodigo[1],
                             Data = as.character(datas_dia),
                             Vazao = as.numeric(NA))
  
  
  for(i in 1:nrow(tabela_final)){
    # Dia em análise
    dia <- as.numeric(substr(tabela_final$Data[i], 9, 10))
    
    # Mês e ano em análise
    mes_ano <- as.Date(paste0(substr(tabela_final$Data[i], 1, 8), "01"))
    
    # Olhar a linha do mes e ano e escolher a coluna pelo dia + 15
    linha_dado <- which(dados_estacao$Data == mes_ano)
    
    # Se não tiver o mês nos dados da estação, colocar valor NA
    ifelse(length(linha_dado) == 0,
           tabela_final$Vazao[i] <- NA,
           tabela_final$Vazao[i] <-
             as.numeric(dados_estacao[linha_dado, (dia + 15)]))
    
  }
  
  return(tabela_final)
}
```


```{r dados_FAL_2}
dados_60435000 <- dados_serie_ANA(cod_estacao = 60435000)
dados_60435000$Data <- as.Date(dados_60435000$Data) 
index_falha_diario <- which(is.na(dados_60435000[,3]==TRUE))
dias_falha <- dados_60435000[index_falha_diario,2:3]
head(dados_60435000)
```

```{r, fig.width = 8, fig.height = 6}
time <- as.Date(dados_60435000$Data)
plot(time,dados_60435000$Vazao,type="l",
     main = "Vazões diárias - estação 60435000",
     xlab = "Anos",ylab = "Q (m3/s)")
# Adiciona grid horizontal apenas
grid(nx = NA, ny = NULL,
     lty = 2,      # Grid line type
     col = "gray", # Grid line color
     lwd = 2)      # Grid line width
```

## Caracterização da distribuição

### Diagramas de caixa (*boxplot*)

### Histograma

### Funções de densidade

## Frequência amostral

## Curva de permanência

## Avaliação de tendência monotônica

## Medidas de associação
